version: '3.7'

services:
    webapp-server:
      build:
        context: .
        dockerfile: Dockerfile
      image: myapp-server-img
      container_name: myapp-node-express
      volumes:
       - .:/usr/src/app
       - /usr/src/app/node_modules
      ports:
        - "8089:8089"
      depends_on:
        - mongo
    mongo:
      image: mongo
      container_name: mongo
      ports:
        - "27017:27017"
      volumes:
        - C:/Program Files/MongoDB/Server/5.0/data:/data/db